# Generated by Django 4.1.3 on 2024-03-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_comment_alter_review_body_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(),
        ),
    ]
