# Generated by Django 4.1.3 on 2024-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="summary",
            field=models.TextField(default="This is Mehrnaz project to learn Django."),
        ),
    ]
