# Generated by Django 4.1.3 on 2024-03-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(default="Whatever you want."),
        ),
    ]
