# Generated by Django 4.1.3 on 2024-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=30)),
                ("LastName", models.CharField(max_length=30)),
                ("age", models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
