# Generated by Django 4.1.3 on 2024-03-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="age",
            field=models.IntegerField(),
        ),
    ]
